// <auto-generated />
using backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace backend.Data.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260720222000_AddGameActiveModifierCostSnapshot")]
    partial class AddGameActiveModifierCostSnapshot
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.28");
#pragma warning restore 612, 618
        }
    }
}
